[book]
authors = ["vivigirardin"]
language = "en"
multilingual = false
src = "documentation"
title = "Data Manangement Handbook for S-ENDA partners"

[build]
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "Ayu"
git-repository-url = "https://github.com/s-ENDA/dmh"
edit-url-template = "https://github.com/s-ENDA/dmh/edit/mdbook/{path}"
no-section-label = false

[output.html.fold] 
enable = true
